# Generated by Django 5.0.1 on 2024-01-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('tsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lib.tsbasemodel')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('lib.tsbasemodel',),
        ),
    ]
