# Generated by Django 5.0.1 on 2024-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0002_sector_parent_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
