# Generated by Django 5.0.1 on 2024-01-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lib', '0001_initial'),
        ('product', '0001_initial'),
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('tsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lib.tsbasemodel')),
                ('name', models.CharField(max_length=500)),
                ('product_templates', models.ManyToManyField(to='product.producttemplate')),
                ('sector', models.ManyToManyField(to='sector.sector', verbose_name='List of Sectors')),
            ],
            bases=('lib.tsbasemodel',),
        ),
    ]
