# Generated by Django 5.0.1 on 2024-01-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('product', '0001_initial'),
        ('sector', '0002_sector_parent_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sector',
        ),
        migrations.AddField(
            model_name='company',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='sector.sector', verbose_name='List of Sectors'),
        ),
        migrations.AlterField(
            model_name='company',
            name='product_templates',
            field=models.ManyToManyField(blank=True, to='product.producttemplate'),
        ),
    ]
